name: auto builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-pub:
    strategy:
      fail-fast: false
      matrix:
        target-os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.target-os }}

    outputs:
      version: ${{ steps.version.outputs }}

    steps:
      - uses: actions/checkout@v3
      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: build
        run: cargo build -r
      
  draft:
    needs: [build-and-pub]
    steps:
      - name: Create a draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{  github.ref_name }}"
          release_name:  ${{  github.ref_name }}"
          body: download ${{  github.ref_name }}" from here or see refer to the README for setup.
          draft: true
